"""Parameter recovery and model recovery analyses.

For each parametric model:
    1. Take the per-subject fitted parameters.
    2. Simulate a synthetic choice sequence for each subject using those parameters,
       holding the observed task structure (delay, time_left, condition) fixed.
    3. Refit every parametric model to the synthetic sequence.
    4. Report:
       a. Parameter recovery: correlation between simulated and recovered parameters
          (within the model family that generated the data).
       b. Model recovery: confusion matrix — for synthetic data generated by model A,
          how often does each candidate model B fit best?

Following Wilson & Collins (2019); Palminteri et al. (2017).
"""

import warnings
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from scipy.stats import pearsonr, spearmanr

from . import config, feature_engineering
from .models import (baselines, historical_dynamics,
                     rl_action_value, rl_state_action, energy_budget)
from .model_simulators import make_simulator

warnings.simplefilter("ignore")


# Models eligible for parameter recovery: those with ≥1 free parameter and a
# deterministic-given-state generative procedure. We skip:
#   - random, bias, logistic (baselines that don't have a meaningful "recovery")
#   - human_as_qtable variants (zero free parameters)
#   - energy_budget_categorical (descriptive, no recoverable parameter)
#   - hill_climbing (relies on inter-click timing which we'd have to simulate)
PARAMETRIC_MODELS = [
    # Energy budget
    ("energy_budget", ["param_beta", "param_scale"]),
    ("energy_budget_threshold", ["param_beta", "param_tau", "param_scale"]),
    ("energy_budget_zscore", ["param_beta"]),
    # Marginal value theorem (rate maximization)
    ("mvt", ["param_beta", "param_scale"]),
    ("mvt_fitted_rho", ["param_beta", "param_rho", "param_scale"]),
    # Historical dynamics (excluding hill_climbing because of ICI complexity)
    ("melioration", ["param_alpha", "param_beta"]),
    ("kinetic", ["param_k", "param_beta"]),
    ("behavioral_momentum", ["param_c", "param_d", "param_beta"]),
    ("ratio_invariance", ["param_omega", "param_beta"]),
    # RL action-value
    ("q_learning", ["param_alpha", "param_beta"]),
    ("q_dual_alpha", ["param_alpha_pos", "param_alpha_neg", "param_beta"]),
    ("q_forgetting", ["param_alpha", "param_beta", "param_forget"]),
    ("q_dynamic_alpha", ["param_alpha_base", "param_alpha_gain", "param_beta", "param_decay"]),
    ("q_condition_aware",
     ["param_alpha_Chicken", "param_alpha_Crab", "param_alpha_Turtle",
      "param_alpha_Piranha", "param_beta"]),
    # RL state-action
    ("q_table_operant", ["param_alpha", "param_beta"]),
    ("q_table_operant_budget", ["param_alpha", "param_beta"]),
]


def simulate_choices(model_name, sdf, params, rng):
    """O(n) rollout using an incremental simulator. Returns a new dataframe
    with synthetic choices/outcomes substituted for the originals."""
    sdf = sdf.reset_index(drop=True)
    n = len(sdf)
    sim_choices = np.zeros(n, dtype=int)
    sim_outcomes = np.zeros(n)

    sim = make_simulator(model_name, params, n_trials=n)
    # Precompute per-cell mean outcomes for the alternative-not-chosen case
    cell_means = (sdf.groupby(["condition", "choice"])["outcome_norm"]
                  .mean().to_dict())

    for t in range(n):
        row = sdf.iloc[t]
        p_ss = float(sim.step(row))
        c = int(rng.uniform() < p_ss)
        sim_choices[t] = c
        # Outcome: observed if simulated choice matches; cell mean otherwise
        obs_choice = int(row["choice"])
        if c == obs_choice:
            sim_outcomes[t] = float(row["outcome_norm"])
        else:
            sim_outcomes[t] = float(cell_means.get((row["condition"], c), 0.0))
        if np.isnan(sim_outcomes[t]):
            sim_outcomes[t] = 0.0
        sim.update(row, c, sim_outcomes[t])

    # Build the working dataframe with synthetic choices/outcomes
    work = sdf.copy()
    work["choice"] = sim_choices
    work["outcome_norm"] = sim_outcomes
    # Recompute prev_choice and prev_outcome under synthetic history within
    # (subject, condition) groups
    work["prev_choice"] = work.groupby("condition")["choice"].shift(1)
    work["prev_outcome"] = work.groupby("condition")["outcome_norm"].shift(1)
    return sim_choices, sim_outcomes, work


N_STARTS_RECOVERY = 3


def _fit_all_families(sdf):
    """Fit every parametric family once and return a dict model_name -> row.
    Replaces per-model dispatch — each family is fit only once."""
    out = {}
    for r in energy_budget.fit_energy_budget(sdf, n_starts=N_STARTS_RECOVERY):
        out[r["model"]] = r
    for r in historical_dynamics.fit_historical(sdf, n_starts=N_STARTS_RECOVERY):
        out[r["model"]] = r
    for r in rl_action_value.fit_rl_action_value(sdf, n_starts=N_STARTS_RECOVERY):
        out[r["model"]] = r
    for r in rl_state_action.fit_state_action_rl(sdf, n_starts=N_STARTS_RECOVERY):
        out[r["model"]] = r
    return out


def _model_fit_dispatch(model_name, sdf):
    """Legacy single-model dispatch — kept for callers that need it."""
    if model_name == "energy_budget":
        rows = energy_budget.fit_energy_budget(sdf, n_starts=N_STARTS_RECOVERY)
        return [r for r in rows if r["model"] == "energy_budget"]
    elif model_name == "energy_budget_threshold":
        rows = energy_budget.fit_energy_budget(sdf, n_starts=N_STARTS_RECOVERY)
        return [r for r in rows if r["model"] == "energy_budget_threshold"]
    elif model_name == "energy_budget_zscore":
        rows = energy_budget.fit_energy_budget(sdf, n_starts=N_STARTS_RECOVERY)
        return [r for r in rows if r["model"] == "energy_budget_zscore"]
    elif model_name in ("mvt", "mvt_fitted_rho"):
        rows = energy_budget.fit_energy_budget(sdf, n_starts=N_STARTS_RECOVERY)
        return [r for r in rows if r["model"] == model_name]
    elif model_name in ("melioration", "kinetic", "behavioral_momentum",
                         "ratio_invariance"):
        rows = historical_dynamics.fit_historical(sdf, n_starts=N_STARTS_RECOVERY)
        return [r for r in rows if r["model"] == model_name]
    elif model_name in ("q_learning", "q_dual_alpha", "q_forgetting",
                         "q_dynamic_alpha", "q_condition_aware"):
        rows = rl_action_value.fit_rl_action_value(sdf, n_starts=5)
        return [r for r in rows if r["model"] == model_name]
    elif model_name in ("q_table_operant", "q_table_operant_budget"):
        rows = rl_state_action.fit_state_action_rl(sdf, n_starts=5)
        return [r for r in rows if r["model"] == model_name]
    return []


def _one_subject_recovery(subject, sdf, fits_for_subject, seed_base=42):
    """For one subject, do the simulate-and-refit cycle for each parametric model."""
    rng = np.random.default_rng(seed_base + hash(subject) % (2**32))
    out_rows = []

    for gen_name, param_names in PARAMETRIC_MODELS:
        # Get the originally fitted parameters for this subject for this model
        fit_row = fits_for_subject[(fits_for_subject["model"] == gen_name) &
                                     (fits_for_subject["scope"] == "all")]
        if len(fit_row) == 0:
            continue
        true_params = fit_row.iloc[0].to_dict()

        # Simulate choices using the fitted parameters
        try:
            sim_choices, sim_outcomes, sim_sdf = simulate_choices(
                gen_name, sdf, true_params, rng)
        except Exception as e:
            continue

        # Refit every parametric model to the synthetic sequence — single
        # family-level pass, not per-model.
        sim_sdf_to_fit = sim_sdf.copy()
        all_fits = _fit_all_families(sim_sdf_to_fit)
        for fit_name, _ in PARAMETRIC_MODELS:
            r = all_fits.get(fit_name)
            if r is None:
                continue
            row = {
                "subject": subject,
                "generator": gen_name,
                "fitter": fit_name,
                "aicc_on_synthetic": r.get("aicc", np.nan),
                "nll_on_synthetic": r.get("nll", np.nan),
                "accuracy_on_synthetic": r.get("accuracy", np.nan),
            }
            # When fitter == generator, record the parameter recovery
            if fit_name == gen_name:
                for p in param_names:
                    row[f"true_{p}"] = true_params.get(p, np.nan)
                    row[f"recovered_{p}"] = r.get(p, np.nan)
            out_rows.append(row)
    return out_rows


def run_parameter_recovery(features_df, fits_df, n_jobs=None, verbose=True):
    n_jobs = n_jobs or config.N_JOBS
    subjects = features_df["subject"].unique()
    if verbose:
        print(f"Running parameter recovery on {len(subjects)} subjects "
              f"across {len(PARAMETRIC_MODELS)} generators × {len(PARAMETRIC_MODELS)} fitters.")

    def _do(sub):
        sdf = features_df[features_df["subject"] == sub].sort_values(
            ["condition", "trial"]).reset_index(drop=True)
        fits_sub = fits_df[fits_df["subject"] == sub]
        return _one_subject_recovery(sub, sdf, fits_sub)

    results = Parallel(n_jobs=n_jobs, verbose=10 if verbose else 0)(
        delayed(_do)(sub) for sub in subjects
    )
    rows = [r for sub_rows in results for r in sub_rows]
    return pd.DataFrame(rows)


def summarize_recovery(recovery_df):
    """Build the two reportable tables:
       (a) per-model parameter recovery correlations (diagonal of the confusion).
       (b) model-recovery confusion matrix (rows = generators, cols = fitters,
           values = % of subjects for whom each fitter won on the synthetic data).
    """
    # --- Parameter recovery on the diagonal ---
    diag = recovery_df[recovery_df["generator"] == recovery_df["fitter"]].copy()
    param_cols = [c for c in diag.columns if c.startswith("true_")]
    param_recovery = []
    for gen in diag["generator"].unique():
        sub = diag[diag["generator"] == gen]
        for col in param_cols:
            pname = col.replace("true_", "")
            true_col = f"true_{pname}"
            rec_col = f"recovered_{pname}"
            if true_col not in sub.columns or rec_col not in sub.columns:
                continue
            paired = sub[[true_col, rec_col]].dropna()
            if len(paired) < 5:
                continue
            try:
                r, p = pearsonr(paired[true_col], paired[rec_col])
                rho, _ = spearmanr(paired[true_col], paired[rec_col])
            except Exception:
                r, rho = np.nan, np.nan
            param_recovery.append({
                "generator": gen,
                "parameter": pname,
                "n": len(paired),
                "pearson_r": r,
                "spearman_rho": rho,
            })
    param_recovery_df = pd.DataFrame(param_recovery)

    # --- Model recovery confusion ---
    winners = (recovery_df.dropna(subset=["aicc_on_synthetic"])
               .groupby(["subject", "generator"])
               .apply(lambda g: g.loc[g["aicc_on_synthetic"].idxmin(), "fitter"])
               .reset_index(name="winner"))
    confusion = (winners.groupby(["generator", "winner"]).size()
                 .unstack(fill_value=0))
    confusion_pct = confusion.div(confusion.sum(axis=1), axis=0) * 100

    return param_recovery_df, confusion, confusion_pct


def main():
    features = pd.read_parquet(config.TRANSFORMED_DIR / "exp1_features.parquet")
    fits = pd.read_parquet(config.RESULTS_DIR / "fits_by_subject.parquet")
    rec = run_parameter_recovery(features, fits)
    out = config.RESULTS_DIR / "parameter_recovery.parquet"
    rec.to_parquet(out, index=False)
    print(f"\nSaved {len(rec)} recovery rows to {out.name}")

    param_df, conf, conf_pct = summarize_recovery(rec)
    param_df.to_parquet(config.RESULTS_DIR / "parameter_recovery_summary.parquet", index=False)
    conf.to_csv(config.RESULTS_DIR / "model_recovery_confusion.csv")
    conf_pct.to_csv(config.RESULTS_DIR / "model_recovery_confusion_pct.csv")

    print("\n=== Parameter Recovery (Pearson r per parameter per generator) ===")
    print(param_df.round(3).to_string(index=False))
    print("\n=== Model Recovery Confusion Matrix (% per row) ===")
    print(conf_pct.round(1).to_string())


if __name__ == "__main__":
    main()
